/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.thiyagu.zally

import org.gradle.testkit.runner.GradleRunner
import java.io.File
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.ExtendWith
import org.junit.jupiter.api.io.TempDir

/**
 * A simple unit test for the 'org.thiyagu.zally.greeting' plugin.
 */
class ZallyGradlePluginTest {

    @Test
    fun `plugin registers task`(@TempDir tempDir: File) {
        File(tempDir, "build.gradle").run {
            writeText(
                """
                        plugins {
                           id("org.thiyagu.zally") version "0.0.2"
                        }
                        zallyLint {
                            inputSpecUrl = "https://raw.githubusercontent.com/zalando/zally/master/examples/sample_swagger_api.yaml"
                        }
                        """
            )
        }

        val buildResult = GradleRunner.create()
            .withProjectDir(tempDir)
            .withPluginClasspath()
            .build()

    }
}
